---

sudo: required

language: python
python:
  - "2.7"

services: docker

branches:
  only:
    - "post-GA7.0.0"

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce

env:
  global:
    - IMAGE=irap/docker-debian-ansible:stretch
  matrix:
    - ANSIBLE_VERSION=2.3.1.0
    - ANSIBLE_VERSION=2.2.3.0

script:
  - wget -O ${PWD}/run.sh https://raw.githubusercontent.com/pari-/docker-debian-ansible/master/run.sh
  - chmod +x ${PWD}/run.sh
  - ${PWD}/run.sh
