---

- hosts: "{{ hosts_group | default('all') }}"

  vars_files:
    - 'example-vars.yml'

  roles:
    - { role: "ansible-nodejs", tags: ['ansible-nodejs'] }
    - { role: "ansible-pm2", tags: ['ansible-pm2'] }
    - { role: "{{ role_name | default('ansible-s3server') }}", tags: ['ansible-s3server'] }
