---

- include: prerequisites.yml
  tags: ['prerequisites']

- include: install.yml
  tags: ['install']

- include: configure.yml
  tags: ['configure']

- include: test.yml
  tags: ['test']
  when: ((s3server_run_tests is defined and s3server_run_tests) and (s3server_credentials is defined and s3server_credentials))
