---

- name: fail unless we run on a supported distribution
  fail:
    msg: "Unfortunately, the 's3server'-role is not supported on {{ ansible_distribution_release }}! :-("
  when: ansible_distribution_release|lower not in s3server_supported_distro_list

- name: install prerequisite packages
  apt:
    default_release: "{{ s3server_pre_default_release }}"
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ s3server_pre_package_list }}"
